dependencies:
  # - <organization/repo@<version> is
  # - smartcontractkit/chainlink-brownie-contracts@1.1.1  # version we're using
  - smartcontractkit/chainlink-brownie-contracts@0.4.0 # actual latest version
compiler:
  solc:
    remappings:
      # - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
      # run 'brownie compile' to bring in these changes
# tells brownie to include .env file to its private, non-push files
dotenv: .env
# define price feeds to be called in .deploy depending on network used
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
# tell brownie which wallets to use
wallets:
  from_key: ${PRIVATE_KEY}

